### ISSUE TITLE
UI Component Library Change Management Process

### ISSUE THREAD

**Issue by bushidocodes** [greymatter-io/gm-ui-components#113]
Once we have multiple consumers consuming UI components from this component library, we're going to be in uncharted waters dealing with design changes. To be frank, the sort of frequent "polish sprints" that Chris Holmes expects inside of an app leading to a demo won't be possible when we're pulling in shared UI components.

We're going to have to have an end-to-end process for designing components that multiple consumers can use safe in the knowledge that the component won't radically look or behave differently when upgrading. To some degree, semantic versioning allows us a bit of flexibility, but I would expect the core UX and functionality to be stable across major version bumps even.

I kinda like the idea of having a process similar to the TC39 process that requires broad consensus from internal stakeholders tied to clearly defined "stages". This would ensure that anyone at the company could propose a "strawman" component and get broad consideration and help from other committee members.
http://2ality.com/2015/11/tc39-process.html

Stage 0 - Strawman. Anyone opens a PR with suggesting a new UI component
Stage 1 - Proposal. A committee member works with the person that opened the PR to create a draft spec for the UI component. This should include a feature branch with a Storybook Story showing the main use cases with links to any external applications or "proto-sketch" the component is pulled from
Stage 2 - Draft. At least two developers have used the component in a GM App or "Fracking Friday" project and validate the developer ergonomics and DX of the component. The API of the component is finalized
Stage 3- Candidate. Feedback from the component should be captured and used to improve the component. The component should have test coverage, type annotations, thorough storybook stories, a theming interface with examples, etc.
Stage 4 - Finished. The component should be generally LOCKED down from major design and UX changes. Changes to the component should require total consensus from all applications consuming the component.

I would suggest that we tag all components in storybook using these tags to clarify stability. I'd expect Stage 1 and Stage 2 components to write console.log warnings to make the warning about instability super clear.

**Comment by tilleryd** [comment]
I like this approach.  The stages provide the expectation for state of progress and risks with versions that are subject to breaking changes.  With GM Data demo UI, GM Documentation, GM Fabric Dashboard, and more in the future we have enough UIs to prove out the components.  One thing we need to consider, is the balance of process and velocity.  I'm inclined to push for the process.  We're always pushing hard which favors velocity.

**Comment by kaitmore** [comment]
@tilleryd @spmcbride1201 

Brad Frost talks about process here: 
http://atomicdesign.bradfrost.com/chapter-5/

**Comment by bushidocodes** [comment]
If we have approval on the Google docs document, I suppose the next step would be to publish in this repo as CONTRIBUTING.md and perhaps get some follow-up issues up for GitHub issues templates and things like that

**Comment by shanberg** [comment]
@bushidocodes I've implemented Adding New Components and Modifying Existing Components as pipelines in GitHub Projects.

**Comment by tilleryd** [comment]
We are comfortable with our current council process.
