### ISSUE TITLE
refactor: change Readout and ReadoutGroup to use CSS Grid

### ISSUE THREAD

**Issue by bushidocodes** [greymatter-io/gm-ui-components#225]
# Modification

## Which component do you want to modify?

ReadoutGroup

## Will this modification effect the existing functionality?

Yes

## Describe your proposed change

Readout and ReadoutGroup currently use flexbox to achieve a fluid responsive layout. This results in readouts having inconsistent widths. I propose refactoring the Readout to be largely layout agnostic (filling parent div) and implementing grid in ReadoutGroup so that Readouts maintain a consistent width when reflowing.

## Supporting Images, Videos, or Links

![image](https://user-images.githubusercontent.com/8700322/41779521-0c053900-7600-11e8-8800-dfa0e21a5253.png)

**Comment by shanberg** [comment]
@bushidocodes I agree that Readouts should be agnostic, but whether we make the container grid or something else should take IE11 support requirements into account.

There are a few other paths we can take to resolve the inconsistent sizing. Flexbox with stricter limitations, grid with flexbox fallback, maybe even an inline-block solution.

**Comment by tilleryd** [comment]
We've decided to not do this in the component lib.
