### ISSUE TITLE
Add ReplicationCard

### ISSUE THREAD

**Issue by kaitmore** [greymatter-io/gm-ui-components#232]
Replication card needs to be refactored from gm-data-ui-prototype and moved into this library https://github.com/DecipherNow/gm-data-ui-prototype/issues/174

**Comment by shanberg** [comment]
Do we still believe this merits a new component?

Perhaps we should consider a base 'Card' wrapper component to handle some light styling?

**Comment by tilleryd** [comment]
Will not implement in lib.
