### ISSUE TITLE
style: upstream Readout design changes from `gm-fabric-dashboard`

### ISSUE THREAD

**Issue by bushidocodes** [greymatter-io/gm-ui-components#238]
# 2. Modification

## Which component do you want to modify?
Readout

## Will this modification effect the exisiting functionality?
No

## Describe your proposed change
Change the design to upstream the changes in src/components/Main/components/Readout/Readout.js in `gm-fabric-dashboard`

**Comment by tilleryd** [comment]
Will not implement in lib.
