### ISSUE TITLE
Rename Threads component to be more abstract

### ISSUE THREAD

**Issue by bushidocodes** [greymatter-io/gm-ui-components#247]
# 2. Modification

## Which component do you want to modify?

Threads glyph

## Will this modification effect the exisiting functionality?

yes. It will break the import of this component in other apps

## Describe your proposed change

The "Threads" component is too opinionated for how its glyph is used.

We are now using it in other contexts

## Supporting Images, Videos, or Links

https://docs.google.com/document/d/19WaT9ZR2Llbff_IBTS5FluvaCFejUwr5LfP-WtXw6Do/edit
![image](https://user-images.githubusercontent.com/8700322/43656421-5d3cbea6-9720-11e8-8501-f3502a8bb694.png)

**Comment by tilleryd** [comment]
Closed in favor of https://github.com/greymatter-io/gm-ui-components/issues/621.
