### ISSUE TITLE
InjectIntl HOC wrap and passing of ClassName to all components that have title/placeholder attributes

### ISSUE THREAD

**Issue by 7ruth** [greymatter-io/gm-ui-components#379]
Components: 

FieldInput
ErrorCard
Checkbox
Button
etc. 

## Describe the new component
- All existing components that need placeholder and/or title (or other attributes, such as aria-attributes) for complete accessibility purposes should allow the final user of the component to pass in intl message object as placeholder/title props without wrapping each single component in this injectIntl HOC. (Lets just do it at the source).

## In what context will the pattern be used?
- GM-ui projects utilize react-intl to enable language locale toggling. For complete accessibility compliance I often want to pass <FormattedMessage /> to the placeholders and titles but I can't pass in JSX component when pure HTML is expected, hence intl lib exposes the injectIntl HOC to handle those cases. 

## Does this pattern have state?
- No

## Progressive enhancement

How does this pattern scale up? 
- This fix would eliminate the need to use injectIntl wrap in all child projects that use react intl prioritize accessibility completeness

How will this pattern degrade in older browsers? 
- All constituents of this issue should work fine in older supported browsers

Does the new component raise any accessibility concerns?
- It closes accessibility gaps by extending language locale toggling capabilities over them.

One concert is that this might throw off testing in projects that currently leverage these components since you would need to use mountWithIntl instead of mount (etc.) in your testing.

**Comment by 7ruth** [comment]
Related https://github.com/DecipherNow/gm-data-ui/issues/190

**Comment by tilleryd** [comment]
Will not address this at this time but will target it as a feature the component library we use as the [new base](https://github.com/greymatter-io/gm-ui-components/issues/619) going forward.
